### ISSUE TITLE
Unable to run the web app

### ISSUE THREAD

**Issue by Caerostris** [lavab/oss#3]
The instructions for the web app appear not to work for me.
What I have done:
1. Fresh Ubuntu 14.04 install in a VM
2. Install nodejs 0.12 and build-essential
3. Install docker
4. As root user, follow lavab/oss instructions till "Web App"

```
cd web
npm install
```

npm install fails to install ws@0.4.32:

```
npm info install ws@0.4.32

> ws@0.4.32 install /root/web/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

Killed
```

`npm install` finishes without errors when re-run after the first, failed, attempt.
However, the next step, `gulp production` fails as well:

```
creating vendor copy task for "LavaMail"...
creating concatenation task for "LavaLoader" application's plugins...
creating concatenation task for "LavaUtils" application's plugins...
creating concatenation task for "LavaLogin" application's plugins...
creating concatenation task for "LavaMail" application's plugins...
[02:49:10] Using gulpfile ~/web/gulpfile.js
/usr/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^
TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:19
    at process._tickDomainCallback (node.js:381:11)
```

All the instructions where completed on a fresh Ubuntu 14.04 installation, so there can't be any conflicts with previously installed software.
Any advise on what I have done wrong?

**Comment by Im4JAR** [comment]
Docker does not work on vm! Thx for your using lavaboom

Von meinem iPhone gesendet

**Comment by pzduniak** [comment]
It obviously does, please do not expect anything from this project.

**Comment by flixi** [comment]
I'm not entirely sure what you've done wrong. Can you run docker ps -a and copy and paste the output here?

**Comment by Caerostris** [comment]
Sure.

```
root@ubuntu:~/web# docker ps -a
CONTAINER ID        IMAGE                                                              COMMAND                CREATED             STATUS                  PORTS                                                                                          NAMES
b85a25d131b9        b76147e75e6a0c550827cb9c8c6230de52b02106ee0ccbb8332f430782e4850c   "/bin/sh -c '. /root   2 days ago          Exited (1) 2 days ago                                                                                                  happy_shockley      
e2bf941aedef        lavab/postfix                                                      "/opt/startup.sh"      2 days ago          Up 2 days               192.168.2.131:2525->25/tcp                                                                     postfix             
ef91d3fe2edd        lavab/spamd                                                        "/bin/sh -c '/usr/sb   2 days ago          Up 2 days               192.168.2.131:783->783/tcp                                                                     spamd               
39c295b6a1d1        nsqio/nsq                                                          "/nsqadmin --lookupd   2 days ago          Up 2 days               4150-4151/tcp, 4160-4161/tcp, 4170/tcp, 192.168.2.131:4171->4171/tcp                           nsqadmin            
3b78b473ead5        nsqio/nsq                                                          "/nsqd --broadcast-a   2 days ago          Up 2 days               4160-4161/tcp, 4170-4171/tcp, 192.168.2.131:4150-4151->4150-4151/tcp                           nsqd                
f14128b5edb4        nsqio/nsq                                                          "/nsqlookupd --broad   2 days ago          Up 2 days               4150-4151/tcp, 4170-4171/tcp, 192.168.2.131:4160-4161->4160-4161/tcp                           nsqlookupd          
69f065f17daf        redis                                                              "/entrypoint.sh redi   2 days ago          Up 2 days               192.168.2.131:6379->6379/tcp                                                                   redis               
4c6818248320        rethinkdb                                                          "rethinkdb --bind al   2 days ago          Up 2 days               192.168.2.131:8080->8080/tcp, 192.168.2.131:28015->28015/tcp, 192.168.2.131:29015->29015/tcp   rethinkdb
```
